### ISSUE TITLE
Combine datasets for Boston property assessments

### ISSUE THREAD

**Issue by tbonza** [sichenghao1992/DS5110Project#2]
* Link to [Boston Property Assessment](https://data.boston.gov/dataset/property-assessment) data. 

Tidy:
- Organize it longer instead of wider. 

Spooky:
- 2017 is missing coordinates because they used GEO_ID or something instead. Impute coordinates using previous years.
- Check for consistencies in the columns (check data dictionaries)

**Comment by SumedhSankhe** [comment]
Data file uploaded, column consistencies are take care of, location coordinates for 2016 and 2017 are WIP
https://drive.google.com/open?id=1rSZWD3yuYf7y0oJ9HULwlUBQEQi6oKeR

**Comment by tbonza** [comment]
Ok cool, thanks! Let me know when 2016 & 2017 are all set then I'll get going on #3

**Comment by SumedhSankhe** [comment]
Okay, the final data is uploaded to the drive I have updated the link [here](https://drive.google.com/open?id=1oYmNlSONLJLyV7TUpd9XSnWwMxmF8L_q),
Latitude and Longitude for 2016 and 2017 have a lot of missing values around  135K in all.
2014 and 2015 have have several missing columns almost 25 as opposed to 2016 to 2017.
I have tried to geocode the missing co-ordinates but the rate limit is 2500, so might have to do sneaky vpn stuff or multiple sessions to impute all of them
