### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by SichengH** [sichenghao1992/DS5110Project#6]
Prepare data for model building. Give group feedback on Wednesday.

**Comment by darkestfloyd** [comment]
@tbonza  and I have worked to fix 83% of missing values, the fixed location data can be found here: https://drive.google.com/open?id=1axooMGkozG8590DXb8PE6ywNTRBZ4Jrn _Be advised, this is not the full data set_ but only the subset with missing LAT and LON attributes.

**Comment by tbonza** [comment]
Data was prepared on time for presentation
